services:
  oops-budgeter:
    image: iconical/oopsbudgeter:latest
    ports:
      - "3333:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CURRENCY=USD
      - PASSCODE=123123
      - JWT_SECRET=Ithinkyouforgottouseyourown32tokencode
      - DATABASE="postgresql://maybelikeauserhere?:andapasswordheretoo?@somerandomipiguess:aportlol/OopsBudgeterDBorsomerandomname?sslmode=require"
    networks:
      - oops-budgeter-network

networks:
  oops-budgeter-network:
    driver: bridge
